// This file is auto-generated. Do not edit manually.
import { ImageSourcePropType } from 'react-native';

export interface CategoryAsset {
  id: string;
  name: string;
  icon: ImageSourcePropType;
  items: { id: string; image: ImageSourcePropType }[];
}

export const ASSETS: Record<string, CategoryAsset> = {
  'animals': {
    id: 'animals',
    name: 'animals',
    icon: require('@assets/images/categories/animals.webp'),
    items: [
      { id: 'bear', image: require('@assets/images/animals/bear.webp') },
      { id: 'cat', image: require('@assets/images/animals/cat.webp') },
      { id: 'chicken', image: require('@assets/images/animals/chicken.webp') },
      { id: 'cow', image: require('@assets/images/animals/cow.webp') },
      { id: 'dog', image: require('@assets/images/animals/dog.webp') },
      { id: 'duck', image: require('@assets/images/animals/duck.webp') },
      { id: 'elephant', image: require('@assets/images/animals/elephant.webp') },
      { id: 'frog', image: require('@assets/images/animals/frog.webp') },
      { id: 'giraffe', image: require('@assets/images/animals/giraffe.webp') },
      { id: 'horse', image: require('@assets/images/animals/horse.webp') },
      { id: 'koala', image: require('@assets/images/animals/koala.webp') },
      { id: 'lion', image: require('@assets/images/animals/lion.webp') },
      { id: 'monkey', image: require('@assets/images/animals/monkey.webp') },
      { id: 'owl', image: require('@assets/images/animals/owl.webp') },
      { id: 'panda', image: require('@assets/images/animals/panda.webp') },
      { id: 'penguin', image: require('@assets/images/animals/penguin.webp') },
      { id: 'rabbit', image: require('@assets/images/animals/rabbit.webp') },
      { id: 'sheep', image: require('@assets/images/animals/sheep.webp') },
      { id: 'tiger', image: require('@assets/images/animals/tiger.webp') },
      { id: 'zebra', image: require('@assets/images/animals/zebra.webp') },
    ]
  },
  'body_parts': {
    id: 'body_parts',
    name: 'body_parts',
    icon: require('@assets/images/categories/body_parts.webp'),
    items: [
      { id: 'body_part_arm', image: require('@assets/images/body_parts/body_part_arm.webp') },
      { id: 'body_part_back', image: require('@assets/images/body_parts/body_part_back.webp') },
      { id: 'body_part_cheek', image: require('@assets/images/body_parts/body_part_cheek.webp') },
      { id: 'body_part_ear', image: require('@assets/images/body_parts/body_part_ear.webp') },
      { id: 'body_part_elbow', image: require('@assets/images/body_parts/body_part_elbow.webp') },
      { id: 'body_part_eye', image: require('@assets/images/body_parts/body_part_eye.webp') },
      { id: 'body_part_face', image: require('@assets/images/body_parts/body_part_face.webp') },
      { id: 'body_part_finger', image: require('@assets/images/body_parts/body_part_finger.webp') },
      { id: 'body_part_foot', image: require('@assets/images/body_parts/body_part_foot.webp') },
      { id: 'body_part_hair', image: require('@assets/images/body_parts/body_part_hair.webp') },
      { id: 'body_part_hand', image: require('@assets/images/body_parts/body_part_hand.webp') },
      { id: 'body_part_head', image: require('@assets/images/body_parts/body_part_head.webp') },
      { id: 'body_part_knee', image: require('@assets/images/body_parts/body_part_knee.webp') },
      { id: 'body_part_leg', image: require('@assets/images/body_parts/body_part_leg.webp') },
      { id: 'body_part_mouth', image: require('@assets/images/body_parts/body_part_mouth.webp') },
      { id: 'body_part_neck', image: require('@assets/images/body_parts/body_part_neck.webp') },
      { id: 'body_part_nose', image: require('@assets/images/body_parts/body_part_nose.webp') },
      { id: 'body_part_shoulder', image: require('@assets/images/body_parts/body_part_shoulder.webp') },
      { id: 'body_part_stomach', image: require('@assets/images/body_parts/body_part_stomach.webp') },
      { id: 'body_part_toes', image: require('@assets/images/body_parts/body_part_toes.webp') },
    ]
  },
  'clothes': {
    id: 'clothes',
    name: 'clothes',
    icon: require('@assets/images/categories/clothes.webp'),
    items: [
      { id: 'belt', image: require('@assets/images/clothes/belt.webp') },
      { id: 'boots', image: require('@assets/images/clothes/boots.webp') },
      { id: 'cap', image: require('@assets/images/clothes/cap.webp') },
      { id: 'coat', image: require('@assets/images/clothes/coat.webp') },
      { id: 'dress', image: require('@assets/images/clothes/dress.webp') },
      { id: 'gloves', image: require('@assets/images/clothes/gloves.webp') },
      { id: 'hat', image: require('@assets/images/clothes/hat.webp') },
      { id: 'jacket', image: require('@assets/images/clothes/jacket.webp') },
      { id: 'pajamas', image: require('@assets/images/clothes/pajamas.webp') },
      { id: 'pants', image: require('@assets/images/clothes/pants.webp') },
      { id: 'raincoat', image: require('@assets/images/clothes/raincoat.webp') },
      { id: 'scarf', image: require('@assets/images/clothes/scarf.webp') },
      { id: 'shirt', image: require('@assets/images/clothes/shirt.webp') },
      { id: 'shoes', image: require('@assets/images/clothes/shoes.webp') },
      { id: 'shorts', image: require('@assets/images/clothes/shorts.webp') },
      { id: 'skirt', image: require('@assets/images/clothes/skirt.webp') },
      { id: 'socks', image: require('@assets/images/clothes/socks.webp') },
      { id: 'sunglasses', image: require('@assets/images/clothes/sunglasses.webp') },
      { id: 'sweater', image: require('@assets/images/clothes/sweater.webp') },
      { id: 't-shirt', image: require('@assets/images/clothes/t-shirt.webp') },
    ]
  },
  'colors': {
    id: 'colors',
    name: 'colors',
    icon: require('@assets/images/categories/colors.webp'),
    items: [
      { id: 'beige_color_splash', image: require('@assets/images/colors/beige_color_splash.webp') },
      { id: 'black_color_splash', image: require('@assets/images/colors/black_color_splash.webp') },
      { id: 'blue_color_splash', image: require('@assets/images/colors/blue_color_splash.webp') },
      { id: 'brown_color_splash', image: require('@assets/images/colors/brown_color_splash.webp') },
      { id: 'cyan_color_splash', image: require('@assets/images/colors/cyan_color_splash.webp') },
      { id: 'dark_blue_color_splash', image: require('@assets/images/colors/dark_blue_color_splash.webp') },
      { id: 'gold_color_splash', image: require('@assets/images/colors/gold_color_splash.webp') },
      { id: 'gray_color_splash', image: require('@assets/images/colors/gray_color_splash.webp') },
      { id: 'green_color_splash', image: require('@assets/images/colors/green_color_splash.webp') },
      { id: 'light_blue_color_splash', image: require('@assets/images/colors/light_blue_color_splash.webp') },
      { id: 'light_green_color_splash', image: require('@assets/images/colors/light_green_color_splash.webp') },
      { id: 'orange_color_splash', image: require('@assets/images/colors/orange_color_splash.webp') },
      { id: 'pink_color_splash', image: require('@assets/images/colors/pink_color_splash.webp') },
      { id: 'purple_color_splash', image: require('@assets/images/colors/purple_color_splash.webp') },
      { id: 'red_color_splash', image: require('@assets/images/colors/red_color_splash.webp') },
      { id: 'silver_color_splash', image: require('@assets/images/colors/silver_color_splash.webp') },
      { id: 'turquoise_color_splash', image: require('@assets/images/colors/turquoise_color_splash.webp') },
      { id: 'violet_color_splash', image: require('@assets/images/colors/violet_color_splash.webp') },
      { id: 'white_color_splash', image: require('@assets/images/colors/white_color_splash.webp') },
      { id: 'yellow_color_splash', image: require('@assets/images/colors/yellow_color_splash.webp') },
    ]
  },
  'electronics': {
    id: 'electronics',
    name: 'electronics',
    icon: require('@assets/images/categories/electronics.webp'),
    items: [
      { id: 'calculator', image: require('@assets/images/electronics/calculator.webp') },
      { id: 'camera', image: require('@assets/images/electronics/camera.webp') },
      { id: 'computer', image: require('@assets/images/electronics/computer.webp') },
      { id: 'fan', image: require('@assets/images/electronics/fan.webp') },
      { id: 'game_controller', image: require('@assets/images/electronics/game_controller.webp') },
      { id: 'headphones', image: require('@assets/images/electronics/headphones.webp') },
      { id: 'keyboard', image: require('@assets/images/electronics/keyboard.webp') },
      { id: 'lamp', image: require('@assets/images/electronics/lamp.webp') },
      { id: 'laptop', image: require('@assets/images/electronics/laptop.webp') },
      { id: 'microwave', image: require('@assets/images/electronics/microwave.webp') },
      { id: 'mouse', image: require('@assets/images/electronics/mouse.webp') },
      { id: 'phone', image: require('@assets/images/electronics/phone.webp') },
      { id: 'printer', image: require('@assets/images/electronics/printer.webp') },
      { id: 'radio', image: require('@assets/images/electronics/radio.webp') },
      { id: 'refrigerator', image: require('@assets/images/electronics/refrigerator.webp') },
      { id: 'smartwatch', image: require('@assets/images/electronics/smartwatch.webp') },
      { id: 'speaker', image: require('@assets/images/electronics/speaker.webp') },
      { id: 'tablet', image: require('@assets/images/electronics/tablet.webp') },
      { id: 'television', image: require('@assets/images/electronics/television.webp') },
      { id: 'washing_machine', image: require('@assets/images/electronics/washing_machine.webp') },
    ]
  },
  'fantasy_creatures': {
    id: 'fantasy_creatures',
    name: 'fantasy_creatures',
    icon: require('@assets/images/categories/fantasy_creatures.webp'),
    items: [
      { id: 'alien', image: require('@assets/images/fantasy_creatures/alien.webp') },
      { id: 'centaur', image: require('@assets/images/fantasy_creatures/centaur.webp') },
      { id: 'dragon', image: require('@assets/images/fantasy_creatures/dragon.webp') },
      { id: 'dwarf', image: require('@assets/images/fantasy_creatures/dwarf.webp') },
      { id: 'elf', image: require('@assets/images/fantasy_creatures/elf.webp') },
      { id: 'fairy', image: require('@assets/images/fantasy_creatures/fairy.webp') },
      { id: 'ghost', image: require('@assets/images/fantasy_creatures/ghost.webp') },
      { id: 'giant', image: require('@assets/images/fantasy_creatures/giant.webp') },
      { id: 'goblin', image: require('@assets/images/fantasy_creatures/goblin.webp') },
      { id: 'griffin', image: require('@assets/images/fantasy_creatures/griffin.webp') },
      { id: 'kraken', image: require('@assets/images/fantasy_creatures/kraken.webp') },
      { id: 'mermaid', image: require('@assets/images/fantasy_creatures/mermaid.webp') },
      { id: 'monster', image: require('@assets/images/fantasy_creatures/monster.webp') },
      { id: 'pegasus', image: require('@assets/images/fantasy_creatures/pegasus.webp') },
      { id: 'phoenix', image: require('@assets/images/fantasy_creatures/phoenix.webp') },
      { id: 'robot', image: require('@assets/images/fantasy_creatures/robot.webp') },
      { id: 'troll', image: require('@assets/images/fantasy_creatures/troll.webp') },
      { id: 'unicorn', image: require('@assets/images/fantasy_creatures/unicorn.webp') },
      { id: 'witch', image: require('@assets/images/fantasy_creatures/witch.webp') },
      { id: 'wizard', image: require('@assets/images/fantasy_creatures/wizard.webp') },
    ]
  },
  'food': {
    id: 'food',
    name: 'food',
    icon: require('@assets/images/categories/food.webp'),
    items: [
      { id: 'apple', image: require('@assets/images/food/apple.webp') },
      { id: 'banana', image: require('@assets/images/food/banana.webp') },
      { id: 'blueberry', image: require('@assets/images/food/blueberry.webp') },
      { id: 'broccoli', image: require('@assets/images/food/broccoli.webp') },
      { id: 'carrot', image: require('@assets/images/food/carrot.webp') },
      { id: 'corn', image: require('@assets/images/food/corn.webp') },
      { id: 'cucumber', image: require('@assets/images/food/cucumber.webp') },
      { id: 'eggplant', image: require('@assets/images/food/eggplant.webp') },
      { id: 'grapes', image: require('@assets/images/food/grapes.webp') },
      { id: 'kiwi', image: require('@assets/images/food/kiwi.webp') },
      { id: 'lemon', image: require('@assets/images/food/lemon.webp') },
      { id: 'mango', image: require('@assets/images/food/mango.webp') },
      { id: 'orange', image: require('@assets/images/food/orange.webp') },
      { id: 'peach', image: require('@assets/images/food/peach.webp') },
      { id: 'pear', image: require('@assets/images/food/pear.webp') },
      { id: 'pineapple', image: require('@assets/images/food/pineapple.webp') },
      { id: 'potato', image: require('@assets/images/food/potato.webp') },
      { id: 'strawberry', image: require('@assets/images/food/strawberry.webp') },
      { id: 'tomato', image: require('@assets/images/food/tomato.webp') },
      { id: 'watermelon', image: require('@assets/images/food/watermelon.webp') },
    ]
  },
  'furniture': {
    id: 'furniture',
    name: 'furniture',
    icon: require('@assets/images/categories/furniture.webp'),
    items: [
      { id: 'bed', image: require('@assets/images/furniture/bed.webp') },
      { id: 'bench', image: require('@assets/images/furniture/bench.webp') },
      { id: 'bookshelf', image: require('@assets/images/furniture/bookshelf.webp') },
      { id: 'cabinet', image: require('@assets/images/furniture/cabinet.webp') },
      { id: 'chair', image: require('@assets/images/furniture/chair.webp') },
      { id: 'coffee_table', image: require('@assets/images/furniture/coffee_table.webp') },
      { id: 'crib', image: require('@assets/images/furniture/crib.webp') },
      { id: 'cupboard', image: require('@assets/images/furniture/cupboard.webp') },
      { id: 'desk', image: require('@assets/images/furniture/desk.webp') },
      { id: 'drawer', image: require('@assets/images/furniture/drawer.webp') },
      { id: 'kitchen_counter', image: require('@assets/images/furniture/kitchen_counter.webp') },
      { id: 'mirror_stand', image: require('@assets/images/furniture/mirror_stand.webp') },
      { id: 'nightstand', image: require('@assets/images/furniture/nightstand.webp') },
      { id: 'rocking_chair', image: require('@assets/images/furniture/rocking_chair.webp') },
      { id: 'shoe_rack', image: require('@assets/images/furniture/shoe_rack.webp') },
      { id: 'sofa', image: require('@assets/images/furniture/sofa.webp') },
      { id: 'stool', image: require('@assets/images/furniture/stool.webp') },
      { id: 'table', image: require('@assets/images/furniture/table.webp') },
      { id: 'tv_stand', image: require('@assets/images/furniture/tv_stand.webp') },
      { id: 'wardrobe', image: require('@assets/images/furniture/wardrobe.webp') },
    ]
  },
  'household_items': {
    id: 'household_items',
    name: 'household_items',
    icon: require('@assets/images/categories/household_items.webp'),
    items: [
      { id: 'blanket', image: require('@assets/images/household_items/blanket.webp') },
      { id: 'broom', image: require('@assets/images/household_items/broom.webp') },
      { id: 'bucket', image: require('@assets/images/household_items/bucket.webp') },
      { id: 'chair', image: require('@assets/images/household_items/chair.webp') },
      { id: 'clock', image: require('@assets/images/household_items/clock.webp') },
      { id: 'comb', image: require('@assets/images/household_items/comb.webp') },
      { id: 'cup', image: require('@assets/images/household_items/cup.webp') },
      { id: 'fork', image: require('@assets/images/household_items/fork.webp') },
      { id: 'lamp', image: require('@assets/images/household_items/lamp.webp') },
      { id: 'mirror', image: require('@assets/images/household_items/mirror.webp') },
      { id: 'pillow', image: require('@assets/images/household_items/pillow.webp') },
      { id: 'plate', image: require('@assets/images/household_items/plate.webp') },
      { id: 'soap', image: require('@assets/images/household_items/soap.webp') },
      { id: 'soap_bottle', image: require('@assets/images/household_items/soap_bottle.webp') },
      { id: 'spoon', image: require('@assets/images/household_items/spoon.webp') },
      { id: 'table', image: require('@assets/images/household_items/table.webp') },
      { id: 'tissue_box', image: require('@assets/images/household_items/tissue_box.webp') },
      { id: 'toothbrush', image: require('@assets/images/household_items/toothbrush.webp') },
      { id: 'towel', image: require('@assets/images/household_items/towel.webp') },
      { id: 'vacuum', image: require('@assets/images/household_items/vacuum.webp') },
    ]
  },
  'musical_instruments': {
    id: 'musical_instruments',
    name: 'musical_instruments',
    icon: require('@assets/images/categories/musical_instruments.webp'),
    items: [
      { id: 'accordion', image: require('@assets/images/musical_instruments/accordion.webp') },
      { id: 'bongos', image: require('@assets/images/musical_instruments/bongos.webp') },
      { id: 'cello', image: require('@assets/images/musical_instruments/cello.webp') },
      { id: 'cymbals', image: require('@assets/images/musical_instruments/cymbals.webp') },
      { id: 'drum', image: require('@assets/images/musical_instruments/drum.webp') },
      { id: 'flute', image: require('@assets/images/musical_instruments/flute.webp') },
      { id: 'guitar', image: require('@assets/images/musical_instruments/guitar.webp') },
      { id: 'harmonica', image: require('@assets/images/musical_instruments/harmonica.webp') },
      { id: 'harp', image: require('@assets/images/musical_instruments/harp.webp') },
      { id: 'maracas', image: require('@assets/images/musical_instruments/maracas.webp') },
      { id: 'piano', image: require('@assets/images/musical_instruments/piano.webp') },
      { id: 'recorder', image: require('@assets/images/musical_instruments/recorder.webp') },
      { id: 'saxophone', image: require('@assets/images/musical_instruments/saxophone.webp') },
      { id: 'tambourine', image: require('@assets/images/musical_instruments/tambourine.webp') },
      { id: 'triangle', image: require('@assets/images/musical_instruments/triangle.webp') },
      { id: 'trumpet', image: require('@assets/images/musical_instruments/trumpet.webp') },
      { id: 'tuba', image: require('@assets/images/musical_instruments/tuba.webp') },
      { id: 'ukulele', image: require('@assets/images/musical_instruments/ukulele.webp') },
      { id: 'violin', image: require('@assets/images/musical_instruments/violin.webp') },
      { id: 'xylophone', image: require('@assets/images/musical_instruments/xylophone.webp') },
    ]
  },
  'nature': {
    id: 'nature',
    name: 'nature',
    icon: require('@assets/images/categories/nature.webp'),
    items: [
      { id: 'branch', image: require('@assets/images/nature/branch.webp') },
      { id: 'bush', image: require('@assets/images/nature/bush.webp') },
      { id: 'cloud', image: require('@assets/images/nature/cloud.webp') },
      { id: 'desert_sand', image: require('@assets/images/nature/desert_sand.webp') },
      { id: 'flower', image: require('@assets/images/nature/flower.webp') },
      { id: 'grass', image: require('@assets/images/nature/grass.webp') },
      { id: 'island', image: require('@assets/images/nature/island.webp') },
      { id: 'leaf', image: require('@assets/images/nature/leaf.webp') },
      { id: 'moon', image: require('@assets/images/nature/moon.webp') },
      { id: 'mountain', image: require('@assets/images/nature/mountain.webp') },
      { id: 'mushroom', image: require('@assets/images/nature/mushroom.webp') },
      { id: 'ocean_wave', image: require('@assets/images/nature/ocean_wave.webp') },
      { id: 'pine_tree', image: require('@assets/images/nature/pine_tree.webp') },
      { id: 'rainbow', image: require('@assets/images/nature/rainbow.webp') },
      { id: 'river', image: require('@assets/images/nature/river.webp') },
      { id: 'star', image: require('@assets/images/nature/star.webp') },
      { id: 'stone', image: require('@assets/images/nature/stone.webp') },
      { id: 'sun', image: require('@assets/images/nature/sun.webp') },
      { id: 'tree', image: require('@assets/images/nature/tree.webp') },
      { id: 'waterfall', image: require('@assets/images/nature/waterfall.webp') },
    ]
  },
  'plants': {
    id: 'plants',
    name: 'plants',
    icon: require('@assets/images/categories/plants.webp'),
    items: [
      { id: 'bamboo', image: require('@assets/images/plants/bamboo.webp') },
      { id: 'bush', image: require('@assets/images/plants/bush.webp') },
      { id: 'cactus', image: require('@assets/images/plants/cactus.webp') },
      { id: 'daisy', image: require('@assets/images/plants/daisy.webp') },
      { id: 'dandelion', image: require('@assets/images/plants/dandelion.webp') },
      { id: 'fern', image: require('@assets/images/plants/fern.webp') },
      { id: 'flower', image: require('@assets/images/plants/flower.webp') },
      { id: 'grass', image: require('@assets/images/plants/grass.webp') },
      { id: 'lavender', image: require('@assets/images/plants/lavender.webp') },
      { id: 'lily', image: require('@assets/images/plants/lily.webp') },
      { id: 'maple_tree', image: require('@assets/images/plants/maple_tree.webp') },
      { id: 'mushroom', image: require('@assets/images/plants/mushroom.webp') },
      { id: 'oak_tree', image: require('@assets/images/plants/oak_tree.webp') },
      { id: 'orchid', image: require('@assets/images/plants/orchid.webp') },
      { id: 'palm_tree', image: require('@assets/images/plants/palm_tree.webp') },
      { id: 'pine_tree', image: require('@assets/images/plants/pine_tree.webp') },
      { id: 'rose', image: require('@assets/images/plants/rose.webp') },
      { id: 'sunflower', image: require('@assets/images/plants/sunflower.webp') },
      { id: 'tulip', image: require('@assets/images/plants/tulip.webp') },
      { id: 'vine', image: require('@assets/images/plants/vine.webp') },
    ]
  },
  'professions': {
    id: 'professions',
    name: 'professions',
    icon: require('@assets/images/categories/professions.webp'),
    items: [
      { id: 'artist', image: require('@assets/images/professions/artist.webp') },
      { id: 'baker', image: require('@assets/images/professions/baker.webp') },
      { id: 'chef', image: require('@assets/images/professions/chef.webp') },
      { id: 'cleaner', image: require('@assets/images/professions/cleaner.webp') },
      { id: 'construction_worker', image: require('@assets/images/professions/construction_worker.webp') },
      { id: 'dentist', image: require('@assets/images/professions/dentist.webp') },
      { id: 'doctor', image: require('@assets/images/professions/doctor.webp') },
      { id: 'driver', image: require('@assets/images/professions/driver.webp') },
      { id: 'farmer', image: require('@assets/images/professions/farmer.webp') },
      { id: 'firefighter', image: require('@assets/images/professions/firefighter.webp') },
      { id: 'librarian', image: require('@assets/images/professions/librarian.webp') },
      { id: 'mechanic', image: require('@assets/images/professions/mechanic.webp') },
      { id: 'musician', image: require('@assets/images/professions/musician.webp') },
      { id: 'nurse', image: require('@assets/images/professions/nurse.webp') },
      { id: 'pilot', image: require('@assets/images/professions/pilot.webp') },
      { id: 'police_officer', image: require('@assets/images/professions/police_officer.webp') },
      { id: 'scientist', image: require('@assets/images/professions/scientist.webp') },
      { id: 'soldier', image: require('@assets/images/professions/soldier.webp') },
      { id: 'teacher', image: require('@assets/images/professions/teacher.webp') },
      { id: 'vet', image: require('@assets/images/professions/vet.webp') },
    ]
  },
  'school_supplies': {
    id: 'school_supplies',
    name: 'school_supplies',
    icon: require('@assets/images/categories/school_supplies.webp'),
    items: [
      { id: 'backpack', image: require('@assets/images/school_supplies/backpack.webp') },
      { id: 'calculator', image: require('@assets/images/school_supplies/calculator.webp') },
      { id: 'chalk', image: require('@assets/images/school_supplies/chalk.webp') },
      { id: 'crayons', image: require('@assets/images/school_supplies/crayons.webp') },
      { id: 'eraser', image: require('@assets/images/school_supplies/eraser.webp') },
      { id: 'folder', image: require('@assets/images/school_supplies/folder.webp') },
      { id: 'glue_stick', image: require('@assets/images/school_supplies/glue_stick.webp') },
      { id: 'highlighter', image: require('@assets/images/school_supplies/highlighter.webp') },
      { id: 'lunchbox', image: require('@assets/images/school_supplies/lunchbox.webp') },
      { id: 'marker', image: require('@assets/images/school_supplies/marker.webp') },
      { id: 'notebook', image: require('@assets/images/school_supplies/notebook.webp') },
      { id: 'paintbrush', image: require('@assets/images/school_supplies/paintbrush.webp') },
      { id: 'pen', image: require('@assets/images/school_supplies/pen.webp') },
      { id: 'pencil', image: require('@assets/images/school_supplies/pencil.webp') },
      { id: 'ruler', image: require('@assets/images/school_supplies/ruler.webp') },
      { id: 'scissors', image: require('@assets/images/school_supplies/scissors.webp') },
      { id: 'sharpener', image: require('@assets/images/school_supplies/sharpener.webp') },
      { id: 'stapler', image: require('@assets/images/school_supplies/stapler.webp') },
      { id: 'watercolor_palette', image: require('@assets/images/school_supplies/watercolor_palette.webp') },
      { id: 'whiteboard', image: require('@assets/images/school_supplies/whiteboard.webp') },
    ]
  },
  'shapes': {
    id: 'shapes',
    name: 'shapes',
    icon: require('@assets/images/categories/shapes.webp'),
    items: [
      { id: 'arrow', image: require('@assets/images/shapes/arrow.webp') },
      { id: 'circle', image: require('@assets/images/shapes/circle.webp') },
      { id: 'cone', image: require('@assets/images/shapes/cone.webp') },
      { id: 'crescent', image: require('@assets/images/shapes/crescent.webp') },
      { id: 'cross', image: require('@assets/images/shapes/cross.webp') },
      { id: 'cube', image: require('@assets/images/shapes/cube.webp') },
      { id: 'cylinder', image: require('@assets/images/shapes/cylinder.webp') },
      { id: 'diamond', image: require('@assets/images/shapes/diamond.webp') },
      { id: 'heart', image: require('@assets/images/shapes/heart.webp') },
      { id: 'hexagon', image: require('@assets/images/shapes/hexagon.webp') },
      { id: 'octagon', image: require('@assets/images/shapes/octagon.webp') },
      { id: 'oval', image: require('@assets/images/shapes/oval.webp') },
      { id: 'pentagon', image: require('@assets/images/shapes/pentagon.webp') },
      { id: 'pyramid', image: require('@assets/images/shapes/pyramid.webp') },
      { id: 'rectangle', image: require('@assets/images/shapes/rectangle.webp') },
      { id: 'ring', image: require('@assets/images/shapes/ring.webp') },
      { id: 'sphere', image: require('@assets/images/shapes/sphere.webp') },
      { id: 'square', image: require('@assets/images/shapes/square.webp') },
      { id: 'star', image: require('@assets/images/shapes/star.webp') },
      { id: 'triangle', image: require('@assets/images/shapes/triangle.webp') },
    ]
  },
  'sports_equipment': {
    id: 'sports_equipment',
    name: 'sports_equipment',
    icon: require('@assets/images/categories/sports_equipment.webp'),
    items: [
      { id: 'baseball_bat', image: require('@assets/images/sports_equipment/baseball_bat.webp') },
      { id: 'baseball_glove', image: require('@assets/images/sports_equipment/baseball_glove.webp') },
      { id: 'basketball', image: require('@assets/images/sports_equipment/basketball.webp') },
      { id: 'bowling_ball', image: require('@assets/images/sports_equipment/bowling_ball.webp') },
      { id: 'boxing_gloves', image: require('@assets/images/sports_equipment/boxing_gloves.webp') },
      { id: 'football', image: require('@assets/images/sports_equipment/football.webp') },
      { id: 'frisbee', image: require('@assets/images/sports_equipment/frisbee.webp') },
      { id: 'golf_club', image: require('@assets/images/sports_equipment/golf_club.webp') },
      { id: 'helmet', image: require('@assets/images/sports_equipment/helmet.webp') },
      { id: 'hockey_stick', image: require('@assets/images/sports_equipment/hockey_stick.webp') },
      { id: 'jump_rope', image: require('@assets/images/sports_equipment/jump_rope.webp') },
      { id: 'ping-pong_paddle', image: require('@assets/images/sports_equipment/ping-pong_paddle.webp') },
      { id: 'roller_skates', image: require('@assets/images/sports_equipment/roller_skates.webp') },
      { id: 'rugby_ball', image: require('@assets/images/sports_equipment/rugby_ball.webp') },
      { id: 'shuttlecock', image: require('@assets/images/sports_equipment/shuttlecock.webp') },
      { id: 'skateboard', image: require('@assets/images/sports_equipment/skateboard.webp') },
      { id: 'soccer_goal', image: require('@assets/images/sports_equipment/soccer_goal.webp') },
      { id: 'swimming_goggles', image: require('@assets/images/sports_equipment/swimming_goggles.webp') },
      { id: 'tennis_racket', image: require('@assets/images/sports_equipment/tennis_racket.webp') },
      { id: 'volleyball', image: require('@assets/images/sports_equipment/volleyball.webp') },
    ]
  },
  'toys': {
    id: 'toys',
    name: 'toys',
    icon: require('@assets/images/categories/toys.webp'),
    items: [
      { id: 'action_figure', image: require('@assets/images/toys/action_figure.webp') },
      { id: 'ball', image: require('@assets/images/toys/ball.webp') },
      { id: 'balloon', image: require('@assets/images/toys/balloon.webp') },
      { id: 'building_blocks', image: require('@assets/images/toys/building_blocks.webp') },
      { id: 'doll', image: require('@assets/images/toys/doll.webp') },
      { id: 'kite', image: require('@assets/images/toys/kite.webp') },
      { id: 'lego_block', image: require('@assets/images/toys/lego_block.webp') },
      { id: 'marble', image: require('@assets/images/toys/marble.webp') },
      { id: 'puzzle_piece', image: require('@assets/images/toys/puzzle_piece.webp') },
      { id: 'robot_toy', image: require('@assets/images/toys/robot_toy.webp') },
      { id: 'rubber_duck', image: require('@assets/images/toys/rubber_duck.webp') },
      { id: 'stuffed_dog', image: require('@assets/images/toys/stuffed_dog.webp') },
      { id: 'stuffed_rabbit', image: require('@assets/images/toys/stuffed_rabbit.webp') },
      { id: 'teddy_bear', image: require('@assets/images/toys/teddy_bear.webp') },
      { id: 'toy_airplane', image: require('@assets/images/toys/toy_airplane.webp') },
      { id: 'toy_boat', image: require('@assets/images/toys/toy_boat.webp') },
      { id: 'toy_car', image: require('@assets/images/toys/toy_car.webp') },
      { id: 'toy_helicopter', image: require('@assets/images/toys/toy_helicopter.webp') },
      { id: 'toy_train', image: require('@assets/images/toys/toy_train.webp') },
      { id: 'yo-yo', image: require('@assets/images/toys/yo-yo.webp') },
    ]
  },
  'vehicles': {
    id: 'vehicles',
    name: 'vehicles',
    icon: require('@assets/images/categories/vehicles.webp'),
    items: [
      { id: 'airplane', image: require('@assets/images/vehicles/airplane.webp') },
      { id: 'ambulance', image: require('@assets/images/vehicles/ambulance.webp') },
      { id: 'bicycle', image: require('@assets/images/vehicles/bicycle.webp') },
      { id: 'boat', image: require('@assets/images/vehicles/boat.webp') },
      { id: 'bus', image: require('@assets/images/vehicles/bus.webp') },
      { id: 'car', image: require('@assets/images/vehicles/car.webp') },
      { id: 'fire_truck', image: require('@assets/images/vehicles/fire_truck.webp') },
      { id: 'helicopter', image: require('@assets/images/vehicles/helicopter.webp') },
      { id: 'hot_air_balloon', image: require('@assets/images/vehicles/hot_air_balloon.webp') },
      { id: 'motorcycle', image: require('@assets/images/vehicles/motorcycle.webp') },
      { id: 'police_car', image: require('@assets/images/vehicles/police_car.webp') },
      { id: 'race_car', image: require('@assets/images/vehicles/race_car.webp') },
      { id: 'rocket', image: require('@assets/images/vehicles/rocket.webp') },
      { id: 'scooter', image: require('@assets/images/vehicles/scooter.webp') },
      { id: 'submarine', image: require('@assets/images/vehicles/submarine.webp') },
      { id: 'tractor', image: require('@assets/images/vehicles/tractor.webp') },
      { id: 'train', image: require('@assets/images/vehicles/train.webp') },
      { id: 'tram', image: require('@assets/images/vehicles/tram.webp') },
      { id: 'truck', image: require('@assets/images/vehicles/truck.webp') },
      { id: 'van', image: require('@assets/images/vehicles/van.webp') },
    ]
  },
  'weather': {
    id: 'weather',
    name: 'weather',
    icon: require('@assets/images/categories/weather.webp'),
    items: [
      { id: 'breeze', image: require('@assets/images/weather/breeze.webp') },
      { id: 'cloud', image: require('@assets/images/weather/cloud.webp') },
      { id: 'cold', image: require('@assets/images/weather/cold.webp') },
      { id: 'fog', image: require('@assets/images/weather/fog.webp') },
      { id: 'hail', image: require('@assets/images/weather/hail.webp') },
      { id: 'heat', image: require('@assets/images/weather/heat.webp') },
      { id: 'hurricane', image: require('@assets/images/weather/hurricane.webp') },
      { id: 'lightning', image: require('@assets/images/weather/lightning.webp') },
      { id: 'rain', image: require('@assets/images/weather/rain.webp') },
      { id: 'rainbow', image: require('@assets/images/weather/rainbow.webp') },
      { id: 'raindrop', image: require('@assets/images/weather/raindrop.webp') },
      { id: 'snow', image: require('@assets/images/weather/snow.webp') },
      { id: 'snowflake', image: require('@assets/images/weather/snowflake.webp') },
      { id: 'storm', image: require('@assets/images/weather/storm.webp') },
      { id: 'sun', image: require('@assets/images/weather/sun.webp') },
      { id: 'sunrise', image: require('@assets/images/weather/sunrise.webp') },
      { id: 'sunset', image: require('@assets/images/weather/sunset.webp') },
      { id: 'thunder', image: require('@assets/images/weather/thunder.webp') },
      { id: 'tornado', image: require('@assets/images/weather/tornado.webp') },
      { id: 'wind', image: require('@assets/images/weather/wind.webp') },
    ]
  },
};

export const CATEGORY_LIST = Object.keys(ASSETS);
